import type {
  StockAsset,
  StockAssetType,
  StockBoardCategory,
  StockBoardPost,
  StockOpinion,
} from "@/types/stock";

export const stockCategories: {
  id: "all" | StockAssetType;
  label: string;
}[] = [
  { id: "all", label: "Tất cả" },
  { id: "domestic", label: "Hàn Quốc" },
  { id: "global", label: "Quốc tế" },
  { id: "coin", label: "Crypto" },
  { id: "index", label: "Chỉ số" },
];

export const stockAssets: StockAsset[] = [
  {
    symbol: "KOSPI",
    displayName: "KOSPI",
    market: "Chỉ số Hàn Quốc",
    tradingViewSymbol: "TVC:KOSPI",
    assetType: "index",
    price: "2,748.52",
    changeRate: 0.74,
    opinionCount: 184,
    bullishPercent: 57,
    bearishPercent: 43,
    chartPoints: [42, 45, 44, 48, 52, 51, 55, 58, 57, 61, 59, 63],
  },
  {
    symbol: "KOSDAQ",
    displayName: "KOSDAQ",
    market: "Chỉ số Hàn Quốc",
    tradingViewSymbol: "KRX:KOSDAQ",
    assetType: "index",
    price: "882.31",
    changeRate: -0.36,
    opinionCount: 151,
    bullishPercent: 48,
    bearishPercent: 52,
    chartPoints: [61, 59, 57, 54, 56, 52, 49, 51, 47, 45, 46, 43],
  },
  {
    symbol: "NASDAQ",
    displayName: "NASDAQ",
    market: "Chỉ số Mỹ",
    tradingViewSymbol: "TVC:NDX",
    assetType: "index",
    price: "19,842.91",
    changeRate: 1.18,
    opinionCount: 236,
    bullishPercent: 62,
    bearishPercent: 38,
    chartPoints: [39, 42, 45, 44, 49, 53, 55, 58, 61, 60, 64, 67],
  },
  {
    symbol: "S&P500",
    displayName: "S&P500",
    market: "Chỉ số Mỹ",
    tradingViewSymbol: "TVC:SPX",
    assetType: "index",
    price: "5,914.22",
    changeRate: 0.63,
    opinionCount: 174,
    bullishPercent: 54,
    bearishPercent: 46,
    chartPoints: [48, 49, 51, 50, 52, 54, 53, 55, 57, 56, 58, 60],
  },
  {
    symbol: "BTCUSDT",
    displayName: "Bitcoin",
    market: "Crypto",
    tradingViewSymbol: "UPBIT:BTCKRW",
    assetType: "coin",
    price: "105,820",
    changeRate: 2.41,
    opinionCount: 298,
    bullishPercent: 64,
    bearishPercent: 36,
    chartPoints: [52, 51, 55, 57, 56, 60, 63, 62, 66, 68, 67, 71],
  },
  {
    symbol: "ETHUSDT",
    displayName: "Ethereum",
    market: "Crypto",
    tradingViewSymbol: "UPBIT:ETHKRW",
    assetType: "coin",
    price: "3,890",
    changeRate: 1.02,
    opinionCount: 126,
    bullishPercent: 55,
    bearishPercent: 45,
    chartPoints: [47, 49, 48, 51, 53, 52, 54, 57, 55, 58, 60, 59],
  },
  {
    symbol: "삼성전자",
    displayName: "Samsung Electronics",
    market: "KOSPI",
    tradingViewSymbol: "KRX:005930",
    assetType: "domestic",
    price: "74,200",
    changeRate: 0.88,
    opinionCount: 214,
    bullishPercent: 58,
    bearishPercent: 42,
    chartPoints: [46, 45, 47, 49, 48, 50, 52, 51, 54, 56, 55, 58],
  },
  {
    symbol: "SK하이닉스",
    displayName: "SK hynix",
    market: "KOSPI",
    tradingViewSymbol: "KRX:000660",
    assetType: "domestic",
    price: "216,500",
    changeRate: -0.82,
    opinionCount: 168,
    bullishPercent: 46,
    bearishPercent: 54,
    chartPoints: [59, 58, 55, 53, 54, 50, 48, 49, 46, 44, 45, 43],
  },
  {
    symbol: "네이버",
    displayName: "NAVER",
    market: "KOSPI",
    tradingViewSymbol: "KRX:035420",
    assetType: "domestic",
    price: "183,400",
    changeRate: 0.21,
    opinionCount: 91,
    bullishPercent: 51,
    bearishPercent: 49,
    chartPoints: [50, 48, 49, 51, 50, 52, 51, 53, 52, 54, 53, 55],
  },
  {
    symbol: "카카오",
    displayName: "Kakao",
    market: "KOSPI",
    tradingViewSymbol: "KRX:035720",
    assetType: "domestic",
    price: "43,700",
    changeRate: -1.34,
    opinionCount: 109,
    bullishPercent: 39,
    bearishPercent: 61,
    chartPoints: [58, 56, 55, 52, 51, 49, 47, 45, 44, 42, 43, 40],
  },
  {
    symbol: "현대차",
    displayName: "Hyundai Motor",
    market: "KOSPI",
    tradingViewSymbol: "KRX:005380",
    assetType: "domestic",
    price: "271,000",
    changeRate: 0.64,
    opinionCount: 118,
    bullishPercent: 56,
    bearishPercent: 44,
    chartPoints: [45, 47, 48, 46, 50, 52, 51, 54, 56, 55, 58, 60],
  },
  {
    symbol: "LG에너지솔루션",
    displayName: "LG Energy Solution",
    market: "KOSPI",
    tradingViewSymbol: "KRX:373220",
    assetType: "domestic",
    price: "356,500",
    changeRate: -0.42,
    opinionCount: 97,
    bullishPercent: 47,
    bearishPercent: 53,
    chartPoints: [55, 54, 52, 53, 50, 48, 49, 47, 46, 44, 45, 43],
  },
  {
    symbol: "한화에어로스페이스",
    displayName: "Hanwha Aerospace",
    market: "KOSPI",
    tradingViewSymbol: "KRX:012450",
    assetType: "domestic",
    price: "319,000",
    changeRate: 1.67,
    opinionCount: 132,
    bullishPercent: 60,
    bearishPercent: 40,
    chartPoints: [45, 47, 50, 49, 53, 55, 54, 57, 60, 58, 62, 64],
  },
  {
    symbol: "테슬라",
    displayName: "Tesla",
    market: "NASDAQ",
    tradingViewSymbol: "NASDAQ:TSLA",
    assetType: "global",
    price: "238.40",
    changeRate: -0.52,
    opinionCount: 201,
    bullishPercent: 49,
    bearishPercent: 51,
    chartPoints: [55, 53, 54, 51, 49, 50, 47, 48, 46, 45, 47, 44],
  },
  {
    symbol: "애플",
    displayName: "Apple",
    market: "NASDAQ",
    tradingViewSymbol: "NASDAQ:AAPL",
    assetType: "global",
    price: "211.18",
    changeRate: 0.47,
    opinionCount: 143,
    bullishPercent: 52,
    bearishPercent: 48,
    chartPoints: [47, 48, 49, 51, 50, 52, 54, 53, 55, 56, 55, 57],
  },
  {
    symbol: "엔비디아",
    displayName: "NVIDIA",
    market: "NASDAQ",
    tradingViewSymbol: "NASDAQ:NVDA",
    assetType: "global",
    price: "144.60",
    changeRate: 2.03,
    opinionCount: 266,
    bullishPercent: 66,
    bearishPercent: 34,
    chartPoints: [44, 47, 49, 52, 54, 57, 59, 61, 64, 63, 66, 69],
  },
  {
    symbol: "금",
    displayName: "Vàng",
    market: "Hàng hóa",
    tradingViewSymbol: "OANDA:XAUUSD",
    assetType: "global",
    price: "2,357.80",
    changeRate: 0.31,
    opinionCount: 88,
    bullishPercent: 52,
    bearishPercent: 48,
    chartPoints: [48, 50, 49, 51, 53, 52, 54, 56, 55, 57, 58, 60],
  },
];

export const mockStockOpinions: StockOpinion[] = [
  {
    id: "stock-profile-opinion-1",
    symbol: "삼성전자",
    userId: "mock-user-semiconductor",
    nickname: "ChipWatcher219",
    avatarType: "chart",
    investorType: "Dài hạn",
    direction: "bullish",
    title: "Nếu giá trị giao dịch tăng, tâm lý có thể đổi",
    body: "Hướng đi vẫn cần thận trọng, nhưng dòng tiền hôm nay có vẻ chắc hơn trước.",
    tags: ["Bán dẫn"],
    timeHorizon: "Tuần này",
    reasons: ["Dòng tiền", "Biểu đồ"],
    createdAt: "10:12",
    likes: 24,
    dislikes: 6,
    commentCount: 6,
  },
  {
    id: "stock-profile-opinion-2",
    symbol: "SK하이닉스",
    userId: "mock-user-ai-watch",
    nickname: "AIWatcher042",
    avatarType: "ai",
    investorType: "Phân tích AI",
    direction: "neutral",
    title: "Vẫn tích cực, nhưng ngắn hạn hơi nóng",
    body: "Nếu nhìn dài hơn thì đáng quan tâm, còn hôm nay giống nhịp quan sát tâm lý hơn.",
    tags: ["AI"],
    timeHorizon: "Tháng này",
    reasons: ["Kết quả", "Tâm lý cộng đồng"],
    createdAt: "10:25",
    likes: 18,
    dislikes: 4,
    commentCount: 4,
  },
  {
    id: "stock-profile-opinion-3",
    symbol: "BTCUSDT",
    userId: "mock-user-volatility",
    nickname: "MarketBeat777",
    avatarType: "flame",
    investorType: "Lướt sóng",
    direction: "bullish",
    title: "Biến động lớn, nhiệt cộng đồng cũng cao",
    body: "Hiện tại ý kiến đang dồn khá mạnh, mình chỉ ghi lại như dữ liệu tham khảo.",
    tags: ["Biến động"],
    timeHorizon: "Hôm nay",
    reasons: ["Biểu đồ", "Cảm nhận"],
    createdAt: "10:44",
    likes: 31,
    dislikes: 9,
    commentCount: 11,
  },
  {
    id: "stock-profile-opinion-4",
    symbol: "카카오",
    userId: "mock-user-wait",
    nickname: "InvestorWait789",
    avatarType: "wave",
    investorType: "Quan sát",
    direction: "bearish",
    title: "Có lẽ nên xác nhận trước khi kỳ vọng hồi",
    body: "Tâm lý cảm nhận vẫn khá nặng, kể cả nhìn ngắn hạn cũng có nhiều ý kiến thận trọng.",
    tags: ["Nền tảng"],
    timeHorizon: "Tuần này",
    reasons: ["Dòng tiền", "Tâm lý cộng đồng"],
    createdAt: "11:08",
    likes: 14,
    dislikes: 8,
    commentCount: 8,
  },
  {
    id: "stock-profile-opinion-5",
    symbol: "엔비디아",
    userId: "mock-user-earnings",
    nickname: "EarningsGame",
    avatarType: "moon",
    investorType: "Cẩn thận quá nóng",
    direction: "bullish",
    title: "Kỳ vọng còn sống, nhưng phải nhìn cả độ nóng",
    body: "Vì ý kiến tích cực khá nhiều nên mình cũng theo dõi thêm góc nhìn ngược lại.",
    tags: ["Kết quả"],
    timeHorizon: "Tháng này",
    reasons: ["Kết quả", "Tin tức"],
    createdAt: "11:22",
    likes: 42,
    dislikes: 12,
    commentCount: 15,
  },
];

export const mockStockBoardPosts: StockBoardPost[] = [
  {
    id: "stock-board-btc-1",
    symbol: "BTCUSDT",
    category: "Biểu đồ",
    title: "Khung 15 phút vẫn chưa rõ hướng",
    body: "Giá đang rung cả hai chiều nên ý kiến bị chia phe. Mình chỉ xem như bản ghi tâm lý cộng đồng, không phải tín hiệu giao dịch.",
    nickname: "ChartReader555",
    createdAt: "10:32",
    views: 184,
    likes: 18,
    dislikes: 5,
    comments: [
      { id: "stock-board-btc-1-comment-1", postId: "stock-board-btc-1", nickname: "StillWatching777", body: "Mình cũng đang nghiêng về quan sát.", createdAt: "10:35", likes: 4, dislikes: 0 },
      { id: "stock-board-btc-1-comment-2", postId: "stock-board-btc-1", nickname: "WaitRebound456", body: "Chỉ đang xem khối lượng có vào không.", createdAt: "10:38", likes: 2, dislikes: 1 },
    ],
  },
  {
    id: "stock-board-btc-2",
    symbol: "BTCUSDT",
    category: "Góc nhìn",
    title: "Hôm nay cảm giác bình luận chạy nhanh hơn tin tức",
    body: "Không phải căn cứ chắc chắn, chỉ là cảm nhận rằng tốc độ phản ứng khá nhanh.",
    nickname: "DCA321",
    createdAt: "11:06",
    views: 97,
    likes: 11,
    dislikes: 3,
    comments: [],
  },
  {
    id: "stock-board-samsung-1",
    symbol: "삼성전자",
    category: "Thông tin",
    title: "Ý kiến về bán dẫn đang tốt hơn, nhưng dòng tiền cần xem thêm",
    body: "Nhiệt cộng đồng đã tốt hơn, nhưng vẫn có nhiều ý kiến cho rằng đây là vùng cần xác nhận.",
    nickname: "WaitRebound456",
    createdAt: "09:58",
    views: 142,
    likes: 16,
    dislikes: 4,
    comments: [
      { id: "stock-board-samsung-1-comment-1", postId: "stock-board-samsung-1", nickname: "LongTerm123", body: "Có lẽ phải xem đến cuối phiên.", createdAt: "10:02", likes: 3, dislikes: 0 },
    ],
  },
];

export const boardCategories: StockBoardCategory[] = [
  "Chung",
  "Câu hỏi",
  "Thông tin",
  "Góc nhìn",
  "Biểu đồ",
  "Phản ứng tin tức",
];

export function getStockHref(symbol: string) {
  return `/stocks/${encodeURIComponent(symbol)}`;
}

export function getStockAssetBySymbol(symbol: string) {
  const normalizedSymbol = decodeURIComponent(symbol);

  return stockAssets.find(
    (stock) =>
      stock.symbol.toLowerCase() === normalizedSymbol.toLowerCase() ||
      stock.displayName.toLowerCase() === normalizedSymbol.toLowerCase(),
  );
}
